name: Makefile CI

on: 
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y flex libfl-dev

      - name: Run build
        run: make build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y flex libfl-dev

      - name: Run tests
        run: make run-tests

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y astyle git

      - name: Run astyle
        run: |
          astyle '*.c' '*.h' '*.cpp' '*.hpp' --recursive --formatted --options=.astylerc --exclude=doctest.h
          if ! git diff --exit-code; then
          echo "Some files were formatted by astyle. Failing the build."
          exit 1
          fi